-- Migration: Add missing EventType enum values
-- MESSAGE_SENT, MESSAGE_RECEIVED, AGENT_START, AGENT_END, LLM_OUTPUT

ALTER TYPE "EventType" ADD VALUE IF NOT EXISTS 'MESSAGE_SENT';
ALTER TYPE "EventType" ADD VALUE IF NOT EXISTS 'MESSAGE_RECEIVED';
ALTER TYPE "EventType" ADD VALUE IF NOT EXISTS 'AGENT_START';
ALTER TYPE "EventType" ADD VALUE IF NOT EXISTS 'AGENT_END';
ALTER TYPE "EventType" ADD VALUE IF NOT EXISTS 'LLM_OUTPUT';
